apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bchchile
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bchchile
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
